# Generated by Django 3.1.7 on 2021-03-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210321_2034'),
        ('portal', '0002_auto_20210313_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='TYSem5',
            fields=[
                ('sub_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_quote', models.CharField(max_length=255)),
                ('sub_image', models.ImageField(default='default.jpg', upload_to='TY_Subjects_Images')),
                ('sub_students', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.tybscit')),
                ('sub_teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
            options={
                'verbose_name_plural': 'TYSem5',
            },
        ),
        migrations.CreateModel(
            name='SYSem3',
            fields=[
                ('sub_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_quote', models.CharField(max_length=255)),
                ('sub_image', models.ImageField(default='default.jpg', upload_to='SY_Subjects_Images')),
                ('sub_students', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.sybscit')),
                ('sub_teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
            options={
                'verbose_name_plural': 'SYSem3',
            },
        ),
        migrations.CreateModel(
            name='FYSem1',
            fields=[
                ('sub_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_quote', models.CharField(max_length=255)),
                ('sub_image', models.ImageField(default='default.jpg', upload_to='FY_Subjects_Images')),
                ('sub_students', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.fybscit')),
                ('sub_teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
            options={
                'verbose_name_plural': 'FYSem1',
            },
        ),
    ]
