# Generated by Django 3.1.7 on 2021-04-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_fysem1_sysem3_tysem5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fysem1',
            old_name='sub_id',
            new_name='subId',
        ),
        migrations.RenameField(
            model_name='fysem1',
            old_name='sub_image',
            new_name='subImage',
        ),
        migrations.RenameField(
            model_name='fysem1',
            old_name='sub_name',
            new_name='subName',
        ),
        migrations.RenameField(
            model_name='fysem1',
            old_name='sub_quote',
            new_name='subQuote',
        ),
        migrations.RenameField(
            model_name='fysem1',
            old_name='sub_students',
            new_name='subStudents',
        ),
        migrations.RenameField(
            model_name='fysem1',
            old_name='sub_teacher',
            new_name='subTeacher',
        ),
        migrations.RenameField(
            model_name='sysem3',
            old_name='sub_id',
            new_name='subId',
        ),
        migrations.RenameField(
            model_name='sysem3',
            old_name='sub_image',
            new_name='subImage',
        ),
        migrations.RenameField(
            model_name='sysem3',
            old_name='sub_name',
            new_name='subName',
        ),
        migrations.RenameField(
            model_name='sysem3',
            old_name='sub_quote',
            new_name='subQuote',
        ),
        migrations.RenameField(
            model_name='sysem3',
            old_name='sub_students',
            new_name='subStudents',
        ),
        migrations.RenameField(
            model_name='sysem3',
            old_name='sub_teacher',
            new_name='subTeacher',
        ),
        migrations.RenameField(
            model_name='tysem5',
            old_name='sub_id',
            new_name='subId',
        ),
        migrations.RenameField(
            model_name='tysem5',
            old_name='sub_image',
            new_name='subImage',
        ),
        migrations.RenameField(
            model_name='tysem5',
            old_name='sub_name',
            new_name='subName',
        ),
        migrations.RenameField(
            model_name='tysem5',
            old_name='sub_quote',
            new_name='subQuote',
        ),
        migrations.RenameField(
            model_name='tysem5',
            old_name='sub_students',
            new_name='subStudents',
        ),
        migrations.RenameField(
            model_name='tysem5',
            old_name='sub_teacher',
            new_name='subTeacher',
        ),
    ]
