# Generated by Django 3.1.7 on 2021-04-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210403_0900'),
        ('portal', '0004_auto_20210403_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fysem1',
            name='subStudents',
        ),
        migrations.AddField(
            model_name='fysem1',
            name='subStudents',
            field=models.ManyToManyField(to='users.Fybscit'),
        ),
    ]
