# Generated by Django 3.1.7 on 2021-04-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210403_0900'),
        ('portal', '0006_auto_20210404_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysem3',
            name='subStudents',
        ),
        migrations.AddField(
            model_name='sysem3',
            name='subStudents',
            field=models.ManyToManyField(to='users.Sybscit'),
        ),
        migrations.RemoveField(
            model_name='sysem3',
            name='subTeacher',
        ),
        migrations.AddField(
            model_name='sysem3',
            name='subTeacher',
            field=models.ManyToManyField(to='users.Teacher'),
        ),
        migrations.RemoveField(
            model_name='tysem5',
            name='subStudents',
        ),
        migrations.AddField(
            model_name='tysem5',
            name='subStudents',
            field=models.ManyToManyField(to='users.Tybscit'),
        ),
        migrations.RemoveField(
            model_name='tysem5',
            name='subTeacher',
        ),
        migrations.AddField(
            model_name='tysem5',
            name='subTeacher',
            field=models.ManyToManyField(to='users.Teacher'),
        ),
    ]
