# Generated by Django 3.1.7 on 2021-04-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210418_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fymonday',
            name='AaronStatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.aaronmonday'),
        ),
        migrations.AlterField(
            model_name='fymonday',
            name='AshokStatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.ashokmonday'),
        ),
        migrations.AlterField(
            model_name='fymonday',
            name='LydiaStatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.lydiamonday'),
        ),
        migrations.AlterField(
            model_name='fymonday',
            name='MelissaStatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.melissamonday'),
        ),
        migrations.AlterField(
            model_name='fymonday',
            name='RachanaStatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.rachanamonday'),
        ),
        migrations.AlterField(
            model_name='fymonday',
            name='RoyStatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.roymonday'),
        ),
        migrations.AlterField(
            model_name='fymonday',
            name='SubhashStatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.subhashmonday'),
        ),
    ]
