# Generated by Django 3.1.7 on 2021-04-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210403_0900'),
        ('portal', '0011_auto_20210418_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyfriday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='fymonday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='fysaturday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='fythursday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='fytuesday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='fywednesday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='syfriday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='symonday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='sysaturday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='sythursday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='sytuesday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='sywednesday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='tyfriday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='tymonday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='tysaturday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='tythursday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='tytuesday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='tywednesday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
