# Generated by Django 3.1.7 on 2021-04-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210403_0900'),
        ('portal', '0012_auto_20210419_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fymonday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='fytuesday',
            name='SubTeacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
