# Generated by Django 3.1.7 on 2021-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20210419_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lydiamonday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
