# Generated by Django 3.1.7 on 2021-04-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20210420_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='lydiamonday',
            name='Class',
            field=models.CharField(blank=True, choices=[('fybscit', 'FY Bsc.IT'), ('sybscit', 'SY BSc.IT'), ('tybscit', 'TY BSc.IT')], max_length=20, null=True),
        ),
    ]
