# Generated by Django 3.1.7 on 2021-04-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_remove_lydiamonday_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fymonday',
            name='LydiaStatus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
