# Generated by Django 3.1.7 on 2021-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20210420_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fymonday',
            name='AaronStatus',
        ),
        migrations.RemoveField(
            model_name='fymonday',
            name='AshokStatus',
        ),
        migrations.RemoveField(
            model_name='fymonday',
            name='LydiaStatus',
        ),
        migrations.RemoveField(
            model_name='fymonday',
            name='MelissaStatus',
        ),
        migrations.RemoveField(
            model_name='fymonday',
            name='RachanaStatus',
        ),
        migrations.RemoveField(
            model_name='fymonday',
            name='RoyStatus',
        ),
        migrations.RemoveField(
            model_name='fymonday',
            name='SubhashStatus',
        ),
        migrations.AddField(
            model_name='fymonday',
            name='LydiStatus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
