# Generated by Django 3.1.7 on 2021-04-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20210420_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fytuesday',
            name='AaronStatus',
        ),
        migrations.RemoveField(
            model_name='fytuesday',
            name='AshokStatus',
        ),
        migrations.RemoveField(
            model_name='fytuesday',
            name='MelissaStatus',
        ),
        migrations.RemoveField(
            model_name='fytuesday',
            name='RachanaStatus',
        ),
        migrations.RemoveField(
            model_name='fytuesday',
            name='RoyStatus',
        ),
        migrations.RemoveField(
            model_name='fytuesday',
            name='SubhashStatus',
        ),
    ]
