# Generated by Django 3.1.7 on 2021-04-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20210421_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='aaronmonday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aaronfriday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aaronsaturday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aaronthursday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aarontuesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aaronwednesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ashokfriday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ashokmonday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ashoksaturday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ashokthursday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ashoktuesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ashokwednesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fyfriday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fymonday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fysaturday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fythursday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fytuesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fywednesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lydiafriday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lydiamonday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lydiasaturday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lydiathursday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lydiatuesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lydiawednesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='melissafriday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='melissamonday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='melissasaturday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='melissathursday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='melissatuesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='melissawednesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rachanafriday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rachanamonday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rachanasaturday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rachanathursday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rachanatuesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rachanawednesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='royfriday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roymonday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roysaturday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roythursday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roytuesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roywednesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subhashfriday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subhashmonday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subhashsaturday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subhashthursday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subhashtuesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subhashwednesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='syfriday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='symonday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sysaturday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sythursday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sytuesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sywednesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tyfriday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tymonday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tysaturday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tythursday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tytuesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tywednesday',
            name='SubStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
