# Generated by Django 3.1.7 on 2021-04-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20210423_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fypapers',
            name='students',
        ),
        migrations.RemoveField(
            model_name='fypapers',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='synotes',
            name='students',
        ),
        migrations.RemoveField(
            model_name='synotes',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='sypapers',
            name='students',
        ),
        migrations.RemoveField(
            model_name='sypapers',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='tynotes',
            name='students',
        ),
        migrations.RemoveField(
            model_name='tynotes',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='typapers',
            name='students',
        ),
        migrations.RemoveField(
            model_name='typapers',
            name='tname',
        ),
        migrations.DeleteModel(
            name='FyNotes',
        ),
        migrations.DeleteModel(
            name='FyPapers',
        ),
        migrations.DeleteModel(
            name='SyNotes',
        ),
        migrations.DeleteModel(
            name='SyPapers',
        ),
        migrations.DeleteModel(
            name='TyNotes',
        ),
        migrations.DeleteModel(
            name='TyPapers',
        ),
    ]
