# Generated by Django 3.1.7 on 2021-04-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
