# Generated by Django 3.1.7 on 2021-04-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210403_0900'),
        ('portal', '0038_fynotes_synotes_sypapers_tynotes_typapers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Class', models.CharField(blank=True, choices=[('fybscit', 'Fy-BScIT'), ('sybscit', 'Sy-BScIT'), ('tybscit', 'Ty-BScIT')], max_length=20, null=True)),
                ('note', models.FileField(upload_to='paper')),
                ('tname', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Class', models.CharField(blank=True, choices=[('fybscit', 'Fy-BScIT'), ('sybscit', 'Sy-BScIT'), ('tybscit', 'Ty-BScIT')], max_length=20, null=True)),
                ('paper', models.FileField(upload_to='paper')),
                ('tname', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='fypapers',
            name='students',
        ),
        migrations.RemoveField(
            model_name='fypapers',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='synotes',
            name='students',
        ),
        migrations.RemoveField(
            model_name='synotes',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='sypapers',
            name='students',
        ),
        migrations.RemoveField(
            model_name='sypapers',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='tynotes',
            name='students',
        ),
        migrations.RemoveField(
            model_name='tynotes',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='typapers',
            name='students',
        ),
        migrations.RemoveField(
            model_name='typapers',
            name='tname',
        ),
        migrations.DeleteModel(
            name='FyNotes',
        ),
        migrations.DeleteModel(
            name='FyPapers',
        ),
        migrations.DeleteModel(
            name='SyNotes',
        ),
        migrations.DeleteModel(
            name='SyPapers',
        ),
        migrations.DeleteModel(
            name='TyNotes',
        ),
        migrations.DeleteModel(
            name='TyPapers',
        ),
    ]
