# Generated by Django 3.1.7 on 2021-04-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_auto_20210424_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='tname',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='papers',
            old_name='tname',
            new_name='professor',
        ),
    ]
