# Generated by Django 3.1.7 on 2021-04-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_auto_20210424_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.FileField(upload_to='notes'),
        ),
    ]
