# Generated by Django 3.1.7 on 2021-04-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_auto_20210424_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Class',
            field=models.CharField(blank=True, choices=[('fybscit', 'FY BSc.IT'), ('sybscit', 'SY BSc.IT'), ('tybscit', 'TY BSc.IT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='Class',
            field=models.CharField(blank=True, choices=[('fybscit', 'FY BSc.IT'), ('sybscit', 'SY BSc.IT'), ('tybscit', 'TY BSc.IT')], max_length=20, null=True),
        ),
    ]
