# Generated by Django 3.1.7 on 2021-04-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210403_0900'),
        ('portal', '0048_auto_20210426_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
