# Generated by Django 2.2.7 on 2021-04-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0056_fysubiinotifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FYSubIINotifications',
        ),
    ]
