# Generated by Django 3.1.7 on 2021-03-18 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210318_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='username',
            new_name='uname',
        ),
    ]
