# Generated by Django 3.1.7 on 2021-03-21 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_auto_20210321_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tybscit',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('stream', models.CharField(default='', max_length=20)),
                ('uname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sybscit',
            },
        ),
        migrations.CreateModel(
            name='Sybscit',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('stream', models.CharField(default='', max_length=20)),
                ('uname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sybscit',
            },
        ),
    ]
