# Generated by Django 3.1.7 on 2021-03-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_sybscit_tybscit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tybscit',
            options={'verbose_name_plural': 'Tybscit'},
        ),
    ]
