# Generated by Django 3.1.7 on 2021-03-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210321_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fybscit',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='sybscit',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='tybscit',
            name='stream',
        ),
    ]
