# Generated by Django 3.1.7 on 2021-04-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210321_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='fybscit',
            name='role',
            field=models.CharField(default='fyStudent', max_length=50),
        ),
        migrations.AddField(
            model_name='sybscit',
            name='role',
            field=models.CharField(default='syStudent', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='Teacher', max_length=50),
        ),
        migrations.AddField(
            model_name='tybscit',
            name='role',
            field=models.CharField(default='tyStudent', max_length=50),
        ),
    ]
